/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HP
 */
public class JFormulario extends javax.swing.JFrame {

    /**
     * Creates new form JFormulario
     */
    public JFormulario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_total1 = new javax.swing.JLabel();
        lbl_producto1 = new javax.swing.JLabel();
        lbl_valor1 = new javax.swing.JLabel();
        txt_nombre1 = new javax.swing.JTextField();
        txt_valor1 = new javax.swing.JTextField();
        txt_total1 = new javax.swing.JTextField();
        lbl_total2 = new javax.swing.JLabel();
        lbl_nombre2 = new javax.swing.JLabel();
        lbl_valor2 = new javax.swing.JLabel();
        txt_total2 = new javax.swing.JTextField();
        txt_nombre2 = new javax.swing.JTextField();
        txt_valor2 = new javax.swing.JTextField();
        lbl_subtotal = new javax.swing.JLabel();
        lbl_descuento = new javax.swing.JLabel();
        lbl_totalfinal = new javax.swing.JLabel();
        txt_totalfinal = new javax.swing.JTextField();
        txt_subtotal = new javax.swing.JTextField();
        txt_descuento = new javax.swing.JTextField();
        btn_calculo3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_total1.setText("PRECIO TOTAL PRODUCTO 1:");
        getContentPane().add(lbl_total1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 210, 20));

        lbl_producto1.setText("INGRESE NOMBRE PRODUCTO 1:");
        getContentPane().add(lbl_producto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 210, 20));

        lbl_valor1.setText("VALOR PRODUCTO 1:");
        getContentPane().add(lbl_valor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 200, 20));
        getContentPane().add(txt_nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 190, -1));

        txt_valor1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(txt_valor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 190, -1));
        getContentPane().add(txt_total1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 190, -1));

        lbl_total2.setText("PRECIO TOTAL PRODUCTO 2:");
        getContentPane().add(lbl_total2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 210, -1));

        lbl_nombre2.setText("INGRESE NOMBRE PRODUCTO 2:");
        getContentPane().add(lbl_nombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 210, -1));

        lbl_valor2.setText("VALOR PRODUCTO 2:");
        getContentPane().add(lbl_valor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 210, -1));
        getContentPane().add(txt_total2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 190, -1));
        getContentPane().add(txt_nombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 190, -1));
        getContentPane().add(txt_valor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 190, -1));

        lbl_subtotal.setText("SUBTOTAL:");
        getContentPane().add(lbl_subtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, -1, -1));

        lbl_descuento.setText("DESCUENTO:");
        getContentPane().add(lbl_descuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, -1, -1));

        lbl_totalfinal.setText("TOTAL:");
        getContentPane().add(lbl_totalfinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, -1, -1));
        getContentPane().add(txt_totalfinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 480, 300, -1));
        getContentPane().add(txt_subtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, 300, -1));
        getContentPane().add(txt_descuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 450, 300, -1));

        btn_calculo3.setText("CALCULAR");
        btn_calculo3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_calculo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calculo3ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_calculo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, -1, -1));

        jLabel2.setText("------------------------------------------------------");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 280, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_calculo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calculo3ActionPerformed
       
        String nombre1;
        int valor1, descuento1,total1;
        valor1=0;
        descuento1=0;
        total1=0;
        
        nombre1=txt_nombre1.getText();
        valor1=Integer.parseInt(txt_valor1.getText());
       
        
        Comprar comprar=new Comprar();
        
        txt_total1.setText(nombre1+" tiene un valor de $ "+comprar.compra_uno(valor1, descuento1, total1));
        
        String nombre2;
       int valor2, descuento2,total2;
       valor2=0;
       descuento2=0;
       total2=0;
       
       nombre2=txt_nombre2.getText();
       valor2=Integer.parseInt(txt_valor2.getText());
       
       
       
       txt_total2.setText(nombre2+" tiene un valor total de $ "+comprar.compra_dos(valor2, descuento2, total2));
        
       
      int subtotal=0;
      txt_subtotal.setText(""+comprar.csubtotal(valor1, descuento1, total1, valor2, descuento2, total2, subtotal));
       
       int t1=0,t2=0, descuento_general=0,descuento_general2=0; 
       
       if(comprar.csubtotal(valor1, descuento1, total1, valor2, descuento2, total2, subtotal)>25000){
           
           txt_descuento.setText("El descuento es de $ "+comprar.descuento1(valor1, descuento1, total1, valor2, descuento2, total2, subtotal, descuento_general));
       
       }else{
           txt_descuento.setText("El descuento es de $ "+comprar.descuento2(valor1, descuento1, total1, valor2, descuento2, total2, subtotal, descuento_general2));
       }
       
       if(comprar.csubtotal(valor1, descuento1, total1, valor2, descuento2, total2, subtotal)>25000){
       
           txt_totalfinal.setText("El precio final es de $ "+comprar.total1(valor1, descuento1, total1, valor2, descuento2, total2, subtotal, descuento_general, t1));
       }else{
           txt_totalfinal.setText("El precio final es de $ "+comprar.total2(valor1, descuento1, total1, valor2, descuento2, total2, subtotal, descuento_general2, t2));
       }
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_btn_calculo3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFormulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_calculo3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbl_descuento;
    private javax.swing.JLabel lbl_nombre2;
    private javax.swing.JLabel lbl_producto1;
    private javax.swing.JLabel lbl_subtotal;
    private javax.swing.JLabel lbl_total1;
    private javax.swing.JLabel lbl_total2;
    private javax.swing.JLabel lbl_totalfinal;
    private javax.swing.JLabel lbl_valor1;
    private javax.swing.JLabel lbl_valor2;
    private javax.swing.JTextField txt_descuento;
    private javax.swing.JTextField txt_nombre1;
    private javax.swing.JTextField txt_nombre2;
    private javax.swing.JTextField txt_subtotal;
    private javax.swing.JTextField txt_total1;
    private javax.swing.JTextField txt_total2;
    private javax.swing.JTextField txt_totalfinal;
    private javax.swing.JTextField txt_valor1;
    private javax.swing.JTextField txt_valor2;
    // End of variables declaration//GEN-END:variables
}
